-- LLM-categorized label for the verbatim pain_point. Generated in the
-- background by categorizePainPoint() using Claude Haiku (temperature 0,
-- ~300ms, ~$0.00003 per call). Stored on the same row so the Insights
-- page can GROUP BY category instead of showing N unique verbatim strings.
--
-- Null means: either no pain_point was captured, or the categorization
-- hasn't run yet (background work in-flight or Haiku was unavailable).
-- The Insights page treats null as "uncategorized" and renders those
-- pain points in a separate bucket.

alter table public.chat_leads
  add column if not exists pain_point_category text;

comment on column public.chat_leads.pain_point_category is
  'Short (2-5 word) LLM-categorized label for the verbatim pain_point. Generated by categorizePainPoint() via Claude Haiku. Null = not yet categorized.';
