// Playbook content and types — the single source for the server-rendered
// detail pages (page.tsx) and the download CTA island.

// Playbook detailed data
export const playbooksData: Record<string, PlaybookDetail> = {
  'post-acquisition-consolidation': {
    slug: 'post-acquisition-consolidation',
    id: 'post-acquisition',
    displayTitle: '40 Systems → One',
    fullTitle: 'Post-Acquisition System Consolidation',
    deployments: 23,
    description: 'Complete playbook for consolidating 30-50 disparate systems post-merger with zero disruption to financial reporting.',
    overview: 'When companies merge or acquire, the immediate challenge isn\'t strategy but rather the chaos of 30-50 disparate systems that don\'t talk to each other. Finance teams spend 40% of their time manually reconciling data across systems, executives can\'t get a unified view of the combined entity, and regulatory compliance becomes a nightmare with no unified audit trail. This playbook documents our battle-tested approach refined across 23 enterprise deployments in financial services, private equity portfolio companies, healthcare, and manufacturing.',
    challengePattern: [
      '30-50 disparate systems from merged entities requiring consolidation with no clear integration path',
      'Multiple data formats with inconsistent standards, definitions, and business rules across legacy systems',
      'Finance teams spending 40%+ of time manually reconciling data instead of strategic analysis',
      'Regulatory compliance (SOX, GDPR, HIPAA) requiring unified audit trails that don\'t exist',
      'Executive mandate for aggressive 12-18 month timeline without any business disruption',
      'Political complexity with different teams owning different systems and resistant to change',
    ],
    solutionApproach: [
      'Phase 1 - Discovery & Assessment: Comprehensive inventory of all systems, data flows, dependencies, and ownership. Identify quick wins vs. complex integrations. Map regulatory requirements.',
      'Phase 2 - Architecture Design: Design target state architecture with unified data model. Define integration patterns (real-time vs. batch). Establish data governance framework.',
      'Phase 3 - Phased Migration: Execute parallel runs with automated validation before each cutover. Start with non-critical systems, build confidence, then migrate core systems.',
      'Phase 4 - Data Quality Gates: Implement automated checks catching 95%+ of issues before they impact downstream systems. Continuous monitoring and alerting.',
      'Phase 5 - Compliance & Audit: SOX compliance by design with audit logging, segregation of duties, and control frameworks built in from day one.',
      'Phase 6 - Change Management: Stakeholder communication plan, user training program, and organizational change management to ensure adoption.',
    ],
    keyLearnings: [
      'Phased migration with parallel runs eliminates cutover risk. Never do "big bang" migrations, they fail 70% of the time.',
      'Automated data quality gates catch 95% of issues before they become business problems. Invest in quality early.',
      'SOX compliance must be designed in from day one. Retrofitting compliance after the fact is 3x more expensive.',
      'Executive sponsorship is critical. Weekly steering committee meetings with C-level attendance ensure blockers are removed fast.',
      'Plan for 30% more complexity than initial assessment suggests. Hidden integrations and undocumented processes always surface.',
      'Political challenges are harder than technical ones. Invest in change management and stakeholder alignment early.',
    ],
    outcomes: [
      { metric: '$9.2M', description: 'Average year-one savings', detail: 'Achieved through process automation, system consolidation, and reduced manual reconciliation effort' },
      { metric: 'Zero', description: 'Financial reporting disruptions', detail: 'All quarterly closes completed on time during migration. No restatements required.' },
      { metric: '78%', description: 'Manual effort reduced', detail: 'Finance team time freed from reconciliation to focus on strategic analysis and business partnering' },
      { metric: '5 days', description: 'Monthly close cycle', detail: 'Reduced from 15 days to 5 days through automated reconciliation and unified reporting' },
    ],
    industries: ['Financial Services', 'Private Equity', 'Healthcare', 'Manufacturing'],
    technologies: ['SAP S/4HANA', 'Python ETL', 'Azure/AWS Data Lakes', 'PowerBI', 'Auto Reconciliation', 'Audit Logging'],
    category: 'Data Engineering',
    timeline: '12-18 months typical',
    teamSize: '15-25 consultants',
    relatedPlaybooks: ['multi-source-integration', 'legacy-cloud-migration'],
    downloadAvailable: false,
  },
  'real-time-data-platform': {
    slug: 'real-time-data-platform',
    id: 'multi-location',
    displayTitle: '600 Stores, Real-Time',
    fullTitle: 'Multi-Location Real-Time Data Platform',
    deployments: 47,
    description: 'Battle-tested architecture for real-time data across 300-1000+ locations with zero tolerance for payment downtime.',
    overview: 'When you operate 300-1000+ physical locations, your data challenges are unique. Every store generates thousands of transactions per hour. Payment processing cannot fail, ever. Marketing wants real-time customer behavior insights, but your legacy batch ETL creates 12-24 hour latency. Weekend traffic spikes hit 3x normal volume, and your infrastructure buckles. This playbook, deployed 47 times across retail chains, QSR franchises, convenience stores, and hospitality groups, provides the battle-tested architecture for distributed real-time data at massive scale.',
    challengePattern: [
      '300-1000+ physical locations each generating thousands of daily transactions that need central visibility',
      'Zero tolerance for payment processing downtime. Even 30 seconds of failure means lost revenue and customer trust.',
      'Marketing and operations need real-time customer behavior insights for personalization and inventory decisions',
      'Legacy batch ETL creates 12-24hr latency, meaning yesterday\'s data drives today\'s decisions',
      'Weekend and holiday traffic spikes hit 3x normal volume, overwhelming infrastructure designed for average load',
      'Store-level connectivity is unreliable. Systems must work when the network doesn\'t.',
    ],
    solutionApproach: [
      'Dual-Write Pattern: Payment data captured at both POS and central platform simultaneously. If central fails, POS continues. Data syncs when connection restores.',
      'Event-Driven Architecture: Kafka/Kinesis streams process transactions in real-time. Events flow to analytics, inventory, and customer platforms within seconds.',
      'Auto-Scaling Infrastructure: Pre-configured scaling policies anticipate predictable traffic patterns. Black Friday, weekends, and lunch rushes handled automatically.',
      'Edge Processing: Critical business logic runs at store level for resilience. Stores operate independently when disconnected, sync when reconnected.',
      'Customer Data Platform: Real-time customer profiles enable instant personalization. Purchase history, preferences, and segments updated within minutes.',
      'Observability First: Dynatrace integration with automated anomaly detection. Issues identified and alerted before customers notice.',
    ],
    keyLearnings: [
      'Payment integration requires dual-write pattern. Never create a single point of failure for revenue-critical systems.',
      'Auto-scaling must be pre-configured for predictable spikes. Reactive scaling is too slow for Black Friday.',
      'Dynatrace observability prevents 90% of production issues before customer impact. Invest in monitoring early.',
      'Store-level edge processing is essential for resilience. Network connectivity to 600+ stores will fail somewhere, always.',
      'Start with 5-10 pilot stores, validate for 4-6 weeks, then roll out in waves of 50-100 stores.',
      'Change data capture (CDC) from POS systems is harder than expected. Budget 30% more time for POS integration.',
    ],
    outcomes: [
      { metric: '<5 min', description: 'Data latency', detail: 'Reduced from 12-24hr batch processing to near real-time streaming' },
      { metric: '99.97%', description: 'Uptime maintained', detail: 'During rollout across all locations with zero payment disruptions' },
      { metric: '3x', description: 'Peak capacity handled', detail: 'Weekend and holiday traffic spikes managed automatically without intervention' },
      { metric: '23%', description: 'Revenue lift', detail: 'From real-time personalization and inventory optimization' },
    ],
    industries: ['Retail', 'QSR/Fast Food', 'Convenience Stores', 'Hospitality'],
    technologies: ['Kafka/Kinesis', 'Databricks Lakehouse', 'Delta Lake', 'Salesforce/Braze CDP', 'Dynatrace', 'Real-time Dashboards'],
    category: 'Data Engineering',
    timeline: '9-15 months typical',
    teamSize: '18-30 consultants',
    relatedPlaybooks: ['global-data-unification', 'self-service-analytics'],
    downloadAvailable: false,
  },
  'global-data-unification': {
    slug: 'global-data-unification',
    id: 'global-unification',
    displayTitle: '55 Countries, One System',
    fullTitle: 'Global Data Unification',
    deployments: 31,
    description: 'Proven approach for unifying data across 40-60 countries with regional silos and inconsistent standards.',
    overview: 'Global enterprises face a unique data challenge: operations span 40-60 countries, each with its own systems, data standards, and compliance requirements. Regional silos mean executives wait weeks for consolidated reports while competitors make decisions in hours. GDPR in Europe, data residency laws in Asia, and varying local regulations create a compliance maze. This playbook, refined through 31 deployments across hospitality chains, manufacturing conglomerates, logistics networks, and professional services firms, provides the proven architecture for global data unification.',
    challengePattern: [
      '40-60 countries operating with independent regional data silos built over decades of local operations',
      'Inconsistent data standards and definitions. "Customer" means different things in different regions.',
      'No unified view of global operations. Executives make decisions based on incomplete, outdated information.',
      'Executive reporting takes 2-3 weeks to compile manually, aggregating spreadsheets from each region',
      'Regional compliance requirements vary dramatically. GDPR in Europe, data residency in Asia, sector regulations everywhere.',
      'Time zone complexity means 24/7 operations with no single "maintenance window" for updates',
    ],
    solutionApproach: [
      'MDM First: Establish master data management for customers, products, and locations before any integration. You cannot integrate what you cannot identify.',
      'Regional Hub Architecture: Data remains in-region for compliance but federates to global view. Respects data residency while enabling global analytics.',
      'Semantic Layer: Business-friendly unified data model that translates regional terminology. "Client" in UK equals "Customer" in US equals "Kunde" in Germany.',
      'API-First Integration: REST/GraphQL APIs for flexibility over rigid batch interfaces. Regions can evolve while maintaining global contract.',
      'Compliance Automation: Built-in data classification, residency enforcement, and audit logging. Compliance is automatic, not manual.',
      'Regional Centers of Excellence: Local teams trained to maintain, extend, and support. Global standards with local ownership.',
    ],
    keyLearnings: [
      'MDM must be established before integration. Attempting to integrate without common identifiers creates a bigger mess.',
      'Regional compliance varies more than expected. Budget 40% more time for compliance mapping and automation.',
      'API integration is more flexible than batch for global deployments. Requirements change constantly in different regions.',
      'Local champions in each region accelerate adoption by 3x. Global mandates without local buy-in fail.',
      'Time zone complexity requires 24/7 support model planning from day one. There is no global maintenance window.',
      'Language and translation affect data quality. "Automated translation" of data values causes more problems than it solves.',
    ],
    outcomes: [
      { metric: 'Same-day', description: 'Executive reporting', detail: 'Reduced from 2-3 weeks manual compilation to automated same-day global dashboards' },
      { metric: '100%', description: 'Global visibility', detail: 'Single unified view across all 55 countries with drill-down to regional detail' },
      { metric: '65%', description: 'Duplicate reduction', detail: 'Master data management eliminated duplicate customer, product, and location records' },
      { metric: 'Zero', description: 'Compliance violations', detail: 'Automated data residency and GDPR compliance with full audit trail' },
    ],
    industries: ['Hospitality', 'Manufacturing', 'Logistics', 'Professional Services'],
    technologies: ['Informatica IICS', 'Master Data Management', 'Cloud Data Lakes', 'API Gateway', 'Global Dashboards', 'Regional Integration'],
    category: 'Data Engineering',
    timeline: '18-24 months typical',
    teamSize: '25-40 consultants',
    relatedPlaybooks: ['real-time-data-platform', 'multi-source-integration'],
    downloadAvailable: false,
  },
  'self-service-analytics': {
    slug: 'self-service-analytics',
    id: 'self-service-analytics',
    displayTitle: '10K Users, Self-Served',
    fullTitle: 'Enterprise Self-Service Analytics',
    deployments: 19,
    description: 'Architecture for enabling 5,000-15,000 users with self-service analytics while maintaining row-level security.',
    overview: 'Your business users are drowning while waiting for data. Every question requires an IT ticket, a 2-week wait, and often a response that doesn\'t quite answer what they needed. Meanwhile, competitors are making data-driven decisions in hours, not weeks. But simply giving everyone access to raw data creates security nightmares, compliance violations, and analysis chaos. This playbook, proven across 19 enterprise deployments, shows how to enable 10,000+ users with self-service analytics while maintaining iron-clad security and governance.',
    challengePattern: [
      '5,000-15,000 end users need regular data access but every request goes through IT',
      'IT data request backlog averages 2 weeks. By the time answers arrive, the business question has changed.',
      'Business users cannot answer time-sensitive questions in real-time, losing competitive opportunities',
      'Row-level security is required. Sales reps should only see their territory. Managers see their team. Executives see everything.',
      'Data literacy varies dramatically. Finance analysts write SQL. Marketing managers need point-and-click.',
      'Shadow IT and spreadsheet chaos emerge as users try to work around IT bottlenecks',
    ],
    solutionApproach: [
      'Row-Level Security by Design: Security model designed upfront based on organizational hierarchy, territory, and role. Every query automatically filtered.',
      'Tiered Access Model: Pre-built dashboards for casual users (80%), self-service exploration for analysts (15%), direct data access for power users (5%).',
      'Semantic Layer: Business-friendly data models hiding joins, calculations, and technical complexity. "Revenue" means the same thing everywhere.',
      'Power User Program: Training and certification creates departmental data champions who help others and reduce IT load.',
      'Governance Framework: Clear policies for data access, sharing, export, and retention. Self-service within guardrails.',
      'Performance Optimization: Pre-aggregated data marts and caching ensure dashboards load in seconds, not minutes.',
    ],
    keyLearnings: [
      'Row-level security must be designed upfront. Retrofitting security after users have access is 3x more expensive and creates compliance gaps.',
      'Pre-configured dashboards satisfy 80% of users. Focus self-service investment on the 20% who need exploration capabilities.',
      'Power user training creates internal champions who drive adoption and reduce IT support burden by 60%.',
      'Semantic layer is essential. Without business-friendly definitions, users create conflicting metrics and lose trust.',
      'Start with one department, prove value, document ROI, then expand. Big-bang rollouts fail.',
      'Performance matters more than features. If dashboards take 30 seconds to load, users abandon them.',
    ],
    outcomes: [
      { metric: '88%', description: 'IT request reduction', detail: 'Users self-serve routine data needs. IT focuses on complex analysis and platform improvements.' },
      { metric: '2 hours', description: 'Time-to-insight', detail: 'Business questions answered in hours instead of 2-week IT backlog' },
      { metric: '92%', description: 'User satisfaction', detail: 'Measured via quarterly surveys. Users report feeling "data empowered."' },
      { metric: '10K+', description: 'Active users', detail: 'Scaled to organization-wide deployment with maintained performance' },
    ],
    industries: ['Financial Services', 'Healthcare', 'Insurance', 'Retail'],
    technologies: ['Databricks Lakehouse', 'Power BI/Tableau', 'Row-Level Security', 'Real-time Refresh', 'Pre-built Dashboards', 'HIPAA Logging'],
    category: 'Analytics',
    timeline: '9-12 months typical',
    teamSize: '12-20 consultants',
    relatedPlaybooks: ['healthcare-data-platform', 'global-data-unification'],
    downloadAvailable: false,
  },
  'healthcare-data-platform': {
    slug: 'healthcare-data-platform',
    id: 'healthcare-data',
    displayTitle: 'HIPAA + GDPR + More',
    fullTitle: 'Multi-Jurisdiction Healthcare Data',
    deployments: 12,
    description: 'Comprehensive playbook for managing patient data across multiple countries with different compliance requirements.',
    overview: 'Healthcare data is uniquely challenging. Patient privacy isn\'t just good practice; it\'s federal law with criminal penalties. And when you operate across borders, you face a patchwork of regulations: HIPAA in the US, GDPR in Europe, PIPEDA in Canada, and dozens of local laws. One misstep means fines, lawsuits, and destroyed trust. Meanwhile, clinical care depends on unified patient data, but your systems have created duplicate records, inconsistent identities, and dangerous gaps. This playbook, refined through 12 deployments across healthcare systems, healthtech companies, clinical research organizations, and pharmaceutical companies, provides the compliance-first architecture for multi-jurisdiction healthcare data.',
    challengePattern: [
      'Patient data distributed across multiple countries, each with different privacy laws and handling requirements',
      'HIPAA in the US, GDPR in Europe, plus dozens of local healthcare privacy regulations that conflict and overlap',
      'No unified patient identity. The same patient appears as 3-5 different records across systems, risking care gaps.',
      'Audit requirements are extremely stringent. Every access must be logged, justified, and reportable for 7+ years.',
      'Clinical system integration requires HL7/FHIR compliance, but legacy systems speak proprietary protocols',
      'Data scientists need access for population health analytics, but PHI exposure risks are significant',
    ],
    solutionApproach: [
      'Compliance-First Architecture: Data classification, handling rules, and access controls are foundational, not afterthoughts. Every data element tagged by sensitivity.',
      'Master Patient Index: Probabilistic matching across name variations, addresses, and demographics creates golden patient record. Reduces duplicates 58%.',
      'Encryption Everywhere: AES-256 at rest, TLS 1.3 in transit. Encryption keys managed through HSM with automatic rotation. No exceptions.',
      'Complete Audit Trail: Every data access logged with user, timestamp, justification, and data accessed. Retention for 7+ years with immutable storage.',
      'Clinical Integration Hub: HL7v2 and FHIR R4 connectors for EHR/EMR systems. Bidirectional sync with conflict resolution.',
      'Research Data Sandbox: De-identified datasets for analytics with re-identification risk monitoring. Researchers get insights without PHI exposure.',
    ],
    keyLearnings: [
      'Compliance must be automated from day one. Manual compliance processes fail at scale and create audit gaps.',
      'Master patient index with fuzzy/probabilistic matching is essential. Exact matching misses 40% of duplicates.',
      'Encryption is baseline, not a feature. Any system handling healthcare data must assume breach attempts.',
      'Audit trail requirements are more extensive than initially understood. Plan for 10x expected storage.',
      'Clinical staff involvement in design is critical. Systems that don\'t fit clinical workflow get worked around.',
      'Data de-identification for research is harder than expected. Re-identification risk assessment is required.',
    ],
    outcomes: [
      { metric: '100%', description: 'Patient identity unified', detail: 'Golden patient record established across all systems and jurisdictions' },
      { metric: '58%', description: 'Duplicate reduction', detail: 'Master patient index eliminated duplicate and fragmented records' },
      { metric: 'Zero', description: 'Compliance violations', detail: 'HIPAA, GDPR, and local healthcare privacy compliance maintained through 3 audits' },
      { metric: '100%', description: 'Audit coverage', detail: 'Every data access logged with complete chain of custody' },
    ],
    industries: ['Healthcare Services', 'Healthcare Tech', 'Clinical Research', 'Pharma'],
    technologies: ['Patient MDM', 'Compliance Automation', 'Encrypted Storage', 'API Gateway', 'Clinical Integration', 'Audit Logging'],
    category: 'Healthcare',
    timeline: '15-24 months typical',
    teamSize: '20-35 consultants',
    relatedPlaybooks: ['self-service-analytics', 'global-data-unification'],
    downloadAvailable: false,
  },
  'supply-chain-visibility': {
    slug: 'supply-chain-visibility',
    id: 'supply-chain',
    displayTitle: 'Supplier → Customer',
    fullTitle: 'Supply Chain Visibility',
    deployments: 28,
    description: 'End-to-end supply chain visibility platform integrating IoT, forecasting, and real-time alerting.',
    overview: 'Supply chain disruptions cost enterprises millions daily. A single container stuck in port, a supplier quality issue, or a demand spike can cascade through your entire operation. Yet most companies operate blind: procurement, logistics, and inventory live in separate systems. Forecasts rely on last quarter\'s data. Disruption response takes days because nobody knows there\'s a problem until customer orders fail. This playbook, battle-tested through 28 deployments across food and beverage, manufacturing, retail, and automotive companies, establishes true end-to-end visibility from raw material supplier to end customer.',
    challengePattern: [
      'Supply chain data scattered across procurement, logistics, inventory, and sales systems with no integration',
      'No end-to-end visibility. When a shipment is delayed, nobody knows until it misses delivery.',
      'Forecasting relies on outdated historical data. Demand spikes and drops create costly stockouts and overstock.',
      'Disruption response is measured in days, not hours. Problems are discovered reactively through customer complaints.',
      'Multiple ERP systems from acquisitions with inconsistent item codes, supplier IDs, and units of measure',
      'Supplier data is unreliable. Lead times, capacity, and quality vary but systems assume static values.',
    ],
    solutionApproach: [
      'Control Tower: Single unified dashboard showing end-to-end supply chain status. From raw material to customer delivery in one view.',
      'IoT Integration: Real-time location and condition tracking for shipments. Temperature, humidity, and shock sensors for sensitive goods.',
      'Supplier Portal: Single source of truth for supplier data. Capacity, lead times, quality scores, and risk indicators updated continuously.',
      'ML Demand Forecasting: Machine learning models incorporating external signals (weather, events, economic indicators) outperform historical trends by 40%.',
      'Real-Time Alerting: Automated detection and escalation of disruptions. Potential issues identified and routed to decision-makers within minutes.',
      'Scenario Planning: What-if simulation for supply chain decisions. Model impact of supplier changes, route alternatives, and demand shifts before committing.',
    ],
    keyLearnings: [
      'IoT integration eliminates blind spots. Sensors cost $10-50 each but save millions in lost shipments and quality issues.',
      'Supplier data standardization is harder than internal data. Budget 2x expected time for supplier onboarding.',
      'ML forecasting models beat historical trends after 6 months of training data. Start collecting signal data early.',
      'Real-time alerting requires clear escalation procedures. Technology without process creates noise, not action.',
      'Start with highest-impact supply chain segments. Prove value in one product line before expanding.',
      'External signals matter. Weather, port congestion, and economic data improve forecasts significantly.',
    ],
    outcomes: [
      { metric: '100%', description: 'E2E visibility', detail: 'Complete tracking from supplier shipment through customer delivery' },
      { metric: '25%', description: 'Carrying cost reduction', detail: 'Optimized inventory levels through accurate demand forecasting' },
      { metric: '4 hours', description: 'Disruption response', detail: 'Reduced from 3 days average to same-day resolution' },
      { metric: '40%', description: 'Forecast accuracy gain', detail: 'ML models outperform historical methods across all product categories' },
    ],
    industries: ['Food & Beverage', 'Manufacturing', 'Retail', 'Automotive'],
    technologies: ['Snowflake/Databricks', 'IoT Integration', 'SAP/Oracle ERP', 'ML Forecasting', 'Tableau/PowerBI', 'Real-time Alerting'],
    category: 'Supply Chain',
    timeline: '12-18 months typical',
    teamSize: '18-28 consultants',
    relatedPlaybooks: ['real-time-data-platform', 'multi-source-integration'],
    downloadAvailable: false,
  },
  'legacy-cloud-migration': {
    slug: 'legacy-cloud-migration',
    id: 'cloud-migration',
    displayTitle: 'Hadoop → Cloud',
    fullTitle: 'Legacy to Cloud Migration',
    deployments: 52,
    description: 'Our most deployed playbook - migrating from aging on-prem Hadoop/Teradata/Oracle to modern cloud with 3x better ROI.',
    overview: 'Your on-premise data platform is becoming a liability. Hadoop clusters need constant care and feeding. Teradata licensing costs grow 15-20% annually. Oracle DBAs are retiring faster than you can hire replacements. Scaling requires 6-12 month hardware procurement cycles while cloud competitors spin up capacity in minutes. Your best data engineers are leaving for companies with modern stacks. This playbook, our most deployed with 52 successful migrations, provides the proven path from legacy on-premise data platforms to modern cloud architectures with zero downtime and 3x better ROI than lift-and-shift.',
    challengePattern: [
      'On-premise Hadoop/Teradata/Oracle platforms are 5-10 years old, approaching end of vendor support',
      'Infrastructure and licensing costs growing 15-20% annually with no corresponding capability improvement',
      'Scaling requires 6-12 month hardware procurement cycles. Business needs capacity now, not next fiscal year.',
      'Maintenance consumes 40%+ of data team time. Engineers patch and tune instead of building value.',
      'Talent retention is failing. Top engineers want cloud experience; they leave for modern shops.',
      'Technical debt accumulates. Workarounds and patches make the platform increasingly fragile.',
    ],
    solutionApproach: [
      'Assessment & Planning: Comprehensive workload analysis categorizing each job by complexity, criticality, and cloud-readiness. Build migration roadmap based on risk and value.',
      'Re-Architecture: Transform workloads for cloud-native benefits. Lift-and-shift misses 70% of cloud value. Re-architecting delivers 3x better ROI.',
      'Parallel Run Strategy: New cloud platform runs alongside legacy for 3-6 months. Results validated against production before cutover.',
      'Automated Migration: Tooling for schema conversion, data movement, and code translation. Manual migration doesn\'t scale.',
      'FinOps from Day One: Cloud cost optimization practices established before migration starts. Prevents cost surprises post-migration.',
      'Team Upskilling: Training and certification program starts 3 months before migration. Teams migrate with knowledge, not fear.',
    ],
    keyLearnings: [
      'Lift-and-shift misses 70% of cloud benefits. Re-architecture is more work upfront but delivers 3x better ROI.',
      'Zero-downtime migration requires parallel run strategy. Plan for 3-6 months of dual operation.',
      'FinOps practices must be established before migration. Cloud costs can exceed on-prem without governance.',
      'Team upskilling should start 3 months before migration. Migrating to a platform nobody understands fails.',
      'Legacy SQL and stored procedures need modernization. Porting bad patterns to cloud creates expensive bad patterns.',
      'Data validation automation is critical. Manual comparison of billion-row tables isn\'t feasible.',
    ],
    outcomes: [
      { metric: '68%', description: 'Cost reduction', detail: 'Infrastructure, licensing, and operational savings versus legacy platform' },
      { metric: '10x', description: 'Processing speed', detail: 'Cloud-native architecture delivers order of magnitude performance improvement' },
      { metric: '$20M', description: '3-year savings', detail: 'Average TCO reduction across mid-size mainframe migrations (~$6.5M/yr against a typical $9-10M/yr baseline). Larger footprints land north of $40M.' },
      { metric: 'Zero', description: 'Downtime', detail: 'Parallel run strategy enables seamless cutover with no business disruption' },
    ],
    industries: ['Financial Services', 'Healthcare', 'Retail', 'Education'],
    technologies: ['AWS/Azure/GCP', 'Databricks/Snowflake', 'Automated Migration Tools', 'Data Validation', 'Terraform IaC', 'Cost Optimization'],
    category: 'Cloud',
    timeline: '9-18 months typical',
    teamSize: '15-30 consultants',
    relatedPlaybooks: ['post-acquisition-consolidation', 'multi-source-integration'],
    downloadAvailable: false,
  },
  'multi-source-integration': {
    slug: 'multi-source-integration',
    id: 'data-integration',
    displayTitle: '40 Sources, One Truth',
    fullTitle: 'Multi-Source Data Integration',
    deployments: 34,
    description: 'Playbook for integrating 20-40 disparate source systems with automated quality detection and self-healing pipelines.',
    overview: 'Your company runs on 40 different systems. Salesforce for CRM. SAP for ERP. Workday for HR. NetSuite for finance. Plus a dozen SaaS tools, legacy databases, Excel spreadsheets from acquisitions, and APIs that seemed like a good idea at the time. Each system is the "source of truth" for something, but they all disagree. Customer names don\'t match. Product codes vary. Revenue numbers never reconcile. This playbook, proven through 34 deployments, provides the architecture for integrating 20-40 disparate systems into a true single source of truth.',
    challengePattern: [
      '20-40 disparate source systems each claiming to be "the source of truth" for different data domains',
      'Mixed landscape: Enterprise SaaS, legacy on-prem databases, department spreadsheets, partner APIs, and acquired company systems',
      'No unified data model. "Customer" has 15 different definitions. "Revenue" calculates differently in every system.',
      'Data quality varies dramatically. CRM is 60% accurate. ERP is 95%. Spreadsheets are anybody\'s guess.',
      'Manual integration processes: analysts copy/paste between systems, creating errors and delays',
      'New data requests take weeks because nobody knows where the data lives or which version is correct',
    ],
    solutionApproach: [
      'Source Discovery: Comprehensive inventory of all data sources, owners, refresh schedules, and data quality. Plan for 3x expected time.',
      'Unified Data Model: Canonical data model that bridges semantic differences across sources. "Customer" means one thing everywhere.',
      'Integration Patterns: Right tool for each source. Batch for daily systems. CDC for real-time. API for SaaS. Direct connect for databases.',
      'Automated Data Quality: Great Expectations or similar for validation. Every record checked against business rules on every load.',
      'Self-Healing Pipelines: Automated retry, error handling, and notification. Failed jobs recover without human intervention 95% of the time.',
      'Data Catalog: Searchable inventory of all data assets. Business users find data in minutes, not weeks.',
    ],
    keyLearnings: [
      'Source system discovery takes 3x longer than expected. Every company has shadow systems nobody documented.',
      'Data quality issues always surface during integration. Automate detection from day one or drown in manual fixes.',
      'CDC (change data capture) is essential for any source requiring real-time or near real-time updates.',
      'Self-healing pipelines reduce operational overhead by 80%. Without them, engineers become babysitters.',
      'Involve source system owners early. They know the edge cases, data quirks, and business rules not documented anywhere.',
      'Data contracts are essential. Source systems must notify before schema changes or face broken integrations.',
    ],
    outcomes: [
      { metric: '32', description: 'Average systems integrated', detail: 'Unified data platform connecting all enterprise data sources' },
      { metric: '85%', description: 'Data quality improvement', detail: 'Automated validation catches issues before they propagate' },
      { metric: '99.8%', description: 'Pipeline reliability', detail: 'Self-healing architecture minimizes downtime and manual intervention' },
      { metric: '80%', description: 'Operational reduction', detail: 'Automation eliminates manual data engineering toil' },
    ],
    industries: ['Technology', 'Financial Services', 'Healthcare', 'Retail'],
    technologies: ['Fivetran/Airbyte', 'Informatica/Mulesoft', 'Databricks/Snowflake', 'Great Expectations', 'Unified Data Model', 'Self-healing Pipelines'],
    category: 'Data Engineering',
    timeline: '6-12 months typical',
    teamSize: '10-20 consultants',
    relatedPlaybooks: ['post-acquisition-consolidation', 'global-data-unification'],
    downloadAvailable: false,
  },
  'agentic-ai-deployment': {
    slug: 'agentic-ai-deployment',
    id: 'agentic-ai',
    displayTitle: 'AI Agent → Workflow',
    fullTitle: 'Enterprise Agentic AI Deployment',
    deployments: 18,
    description: 'Production playbook for deploying AI agents that make autonomous decisions within bounded parameters—from multi-agent orchestration to legacy system integration.',
    overview: 'Everyone has an AI agent demo. Almost no one has agents in production. Gartner predicts 40% of agentic AI projects will fail by 2027—not because the models don\'t work, but because enterprises underestimate what production means. Your agents aren\'t failing because of hallucinations. They\'re failing because they\'re making decisions with 20% of the information they need. The other 80%—contracts, email threads, negotiated rates, policy documents—is invisible to them. This playbook addresses the real blockers: legacy system integration, multi-agent orchestration, bounded autonomy architectures, and the governance infrastructure that lets you trust agents with actual decisions. The result: agents that operate autonomously within defined boundaries, escalate appropriately, and create audit trails your compliance team accepts.',
    challengePattern: [
      'Agents making enterprise decisions with only 20% of required context—the rest locked in legacy systems, emails, and documents',
      'Multi-agent orchestration without clear handoff protocols, escalation paths, or conflict resolution between specialized agents',
      'Legacy systems lacking real-time APIs, modern authentication, and the modular architecture that agents require',
      'No clear boundaries between what agents decide autonomously vs. what requires human approval',
      'Scaling costs 10x from pilot to production without proportional value increase—what costs $50/day becomes $50,000/day',
      'Security and compliance teams blocking deployment due to insufficient audit trails and explainability',
    ],
    solutionApproach: [
      'Context Architecture: Map all data sources agents need. Build integration layer that surfaces contracts, communications, and institutional knowledge—not just structured data.',
      'Bounded Autonomy Design: Define explicit decision boundaries. What can agents do alone? What requires human review? What\'s completely off-limits?',
      'Multi-Agent Orchestration: Design agent handoff protocols, shared state management, conflict resolution, and escalation paths before building individual agents.',
      'Legacy Integration Layer: API gateway approach for systems that weren\'t designed for real-time agent interaction. Prioritize high-value data access.',
      'Production Hardening: Comprehensive monitoring, circuit breakers, fallback behaviors, and cost controls. Treat agents like any mission-critical system.',
      'Governance Integration: Audit trails, explainability layers, and compliance hooks designed in from day one—not retrofitted after deployment.',
    ],
    keyLearnings: [
      'Context access is the real blocker—most agents fail not from hallucination but from information starvation.',
      'Bounded autonomy beats full autonomy: define explicit guardrails rather than hoping agents make good judgment calls.',
      'Multi-agent orchestration is an architectural problem, not a prompt engineering problem.',
      'Legacy integration takes 3x longer than expected—plan for it or watch your timeline slip.',
      'Production costs don\'t scale linearly: architect for efficiency before pilot ends or face budget rejection.',
      'Governance agents monitoring other agents is emerging best practice for enterprise deployments.',
    ],
    outcomes: [
      { metric: '40-60%', description: 'Faster operational cycles', detail: 'Autonomous agent execution accelerates routine decision-making and workflow processing' },
      { metric: '30-50%', description: 'More consistent decisions', detail: 'Agent-driven processes reduce variability compared to human-only execution' },
      { metric: '2-3x', description: 'Operational scale', detail: 'Handle increased volume without proportional headcount growth' },
      { metric: '100%', description: 'Audit trail coverage', detail: 'Every agent decision logged with full explainability for compliance' },
    ],
    industries: ['Financial Services', 'Healthcare', 'Retail', 'Technology', 'Manufacturing'],
    technologies: ['LangChain/LlamaIndex', 'Azure OpenAI/AWS Bedrock', 'Vector Databases', 'Kubernetes', 'Apache Kafka', 'Agent Orchestration Platforms', 'API Gateways'],
    category: 'AI & ML',
    timeline: '6-12 months typical',
    teamSize: '10-20 consultants',
    relatedPlaybooks: ['enterprise-ai-governance', 'multi-source-integration'],
    downloadAvailable: false,
  },
  'enterprise-ai-governance': {
    slug: 'enterprise-ai-governance',
    id: 'ai-governance',
    displayTitle: 'Governed AI',
    fullTitle: 'Enterprise AI Governance & Compliance',
    deployments: 14,
    description: 'Operational AI governance framework covering shadow AI detection, model risk management, regulatory compliance (EU AI Act), and audit infrastructure—not just bias policies.',
    overview: 'Your AI governance policy is impressive. Your AI governance reality is chaos. 65% of AI tools in the average enterprise operate without IT oversight. Shadow AI already accounts for 20% of data breaches, adding $670,000 to incident costs. Meanwhile, the EU AI Act takes effect August 2026 with fines up to €35 million or 7% of global revenue. Most governance frameworks fail because they\'re built for a world where AI deployments are centralized and controlled. That world is gone. Employees use ChatGPT in spreadsheets. Teams deploy models without approval. Vendors embed AI in products you already purchased. This playbook builds governance that works in reality: automated discovery, continuous monitoring, risk-tiered controls, and audit infrastructure that proves compliance without creating bottlenecks. The result: AI that moves fast because governance enables it rather than blocking it.',
    challengePattern: [
      'Shadow AI proliferating faster than governance can track—employees using unauthorized AI tools with sensitive data daily',
      'No inventory of AI systems in production, development, or embedded in vendor products you already purchased',
      'EU AI Act, CCPA, HIPAA, and industry regulations each requiring different controls with overlapping deadlines',
      'Model drift degrading performance over time with no systematic detection or remediation process',
      'Audit requests requiring weeks of manual evidence gathering that still produces incomplete documentation',
      'Governance perceived as bottleneck—teams routing around controls rather than working within them',
    ],
    solutionApproach: [
      'AI Asset Discovery: Automated scanning for AI usage across the enterprise—sanctioned tools, shadow deployments, vendor-embedded AI. You can\'t govern what you can\'t see.',
      'Risk-Tiered Framework: Classify AI by risk level aligned to EU AI Act categories. High-risk systems get intensive controls. Low-risk moves fast with light oversight.',
      'Continuous Monitoring: Model performance tracking, drift detection, and anomaly alerting. Move from point-in-time validation to ongoing assurance.',
      'Automated Compliance: Map regulations to controls once, generate evidence continuously. Audit-ready documentation without manual assembly.',
      'Integrated Audit Trail: Every model decision logged with inputs, outputs, version, and lineage. Immutable records for regulatory inspection.',
      'Governance-as-Enabler: Self-service risk assessment, pre-approved patterns, fast-track for low-risk use cases. Make the governed path the easy path.',
    ],
    keyLearnings: [
      'Shadow AI is the real risk—not the models you know about, but the ones you don\'t.',
      'Prohibition drives AI underground; enablement with guardrails brings it into governance.',
      'Model drift is continuous—governance must be continuous monitoring, not annual audits.',
      'Risk tiering prevents governance from becoming a bottleneck—not every model needs the same scrutiny.',
      'Automated evidence generation is essential—manual compliance doesn\'t scale.',
      'Integrate with existing GRC frameworks (COBIT, ERM) rather than creating parallel governance structures.',
    ],
    outcomes: [
      { metric: '100%', description: 'AI visibility', detail: 'Complete inventory of AI systems across the enterprise including shadow AI' },
      { metric: 'Multi-reg', description: 'Compliance ready', detail: 'Single framework handles EU AI Act, CCPA, HIPAA, and industry requirements' },
      { metric: '70%', description: 'Faster audits', detail: 'Automated evidence generation eliminates manual documentation assembly' },
      { metric: '<5 days', description: 'Governance cycle', detail: 'Standard-risk AI deployments approved in under a week, not months' },
    ],
    industries: ['Financial Services', 'Healthcare', 'Insurance', 'Government', 'Regulated Industries'],
    technologies: ['AI Discovery Platforms', 'MLflow/Weights & Biases', 'Model Monitoring (Evidently AI, Arize)', 'GRC Integration', 'Audit Trail Infrastructure', 'SHAP/Explainability Tools'],
    category: 'AI & ML',
    timeline: '8-14 months typical',
    teamSize: '8-15 consultants',
    relatedPlaybooks: ['agentic-ai-deployment', 'healthcare-data-platform'],
    downloadAvailable: false,
  },
};

export interface PlaybookDetail {
  slug: string;
  id: string;
  displayTitle: string;
  fullTitle: string;
  deployments: number;
  description: string;
  overview: string;
  challengePattern: string[];
  solutionApproach: string[];
  keyLearnings: string[];
  outcomes: { metric: string; description: string; detail: string }[];
  industries: string[];
  technologies: string[];
  category: string;
  timeline: string;
  teamSize: string;
  relatedPlaybooks: string[];
  downloadAvailable: boolean;
}
