#!/usr/bin/env tsx
/**
 * Build src/lib/copilot/entityIndex.generated.ts.
 *
 * Produces a client-safe slug->{panelType,title} index from:
 *   - LP_CONTENT (src/lib/lp-content.ts)
 *   - services (src/data/services.ts)
 *   - industries (src/data/industries.ts)
 *   - platforms (src/data/platforms.ts)
 *   - the static diagram registry
 *
 * The generated module carries no secrets, no real client names (case
 * studies are keyed by slug, not by any client identifier), and is
 * checked into git so the client does not need to run this script
 * before a dev build.
 *
 * Run:
 *   cd aci-infotech
 *   npx tsx scripts/build-entity-index.ts
 */
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { LP_CONTENT } from '../src/lib/lp-content';
import { services } from '../src/data/services';
import { industries } from '../src/data/industries';
import { platforms } from '../src/data/platforms';
import { DIAGRAM_KEYS } from '../src/components/copilot/diagrams/registry';

type Entry = { panelType: string; title: string };
const entries: Record<string, Entry> = {};

for (const lp of Object.values(LP_CONTENT)) {
  entries[lp.slug] = { panelType: 'resource', title: lp.headline ?? lp.slug };
}
for (const s of Object.values(services)) {
  entries[s.slug] = { panelType: 'service', title: s.title };
  for (const cs of s.caseStudies ?? []) {
    if (cs.slug) entries[cs.slug] = { panelType: 'case', title: cs.challenge };
  }
}
for (const i of Object.values(industries)) {
  entries[i.slug] = { panelType: 'industry', title: i.title };
  for (const cs of i.caseStudies ?? []) {
    if (cs.slug) entries[cs.slug] = { panelType: 'case', title: cs.challenge };
  }
}
for (const p of Object.values(platforms)) {
  entries[p.slug] = { panelType: 'platform', title: p.title };
  for (const cs of p.caseStudies ?? []) {
    if (cs.slug) entries[cs.slug] = { panelType: 'case', title: cs.challenge };
  }
}
for (const d of DIAGRAM_KEYS) {
  entries[d] = { panelType: 'diagram', title: d };
}

const outPath = join(
  new URL('..', import.meta.url).pathname,
  'src/lib/copilot/entityIndex.generated.ts',
);

const body = `/**
 * GENERATED by scripts/build-entity-index.ts. Do not edit by hand.
 * Re-run the script after adding a new LP, service, industry, platform,
 * case study, or diagram.
 */
import type { PanelType } from '@/components/copilot/panels/registry';

export interface EntityIndexEntry {
  panelType: PanelType;
  title: string;
}

export const ENTITY_INDEX: Readonly<Record<string, EntityIndexEntry>> = ${JSON.stringify(
  entries,
  null,
  2,
)} as const;

export function resolveEntity(entityRef: string): EntityIndexEntry | undefined {
  return ENTITY_INDEX[entityRef];
}
`;

writeFileSync(outPath, body);
console.log(`[entity-index] wrote ${Object.keys(entries).length} entries -> ${outPath}`);
