/**
 * GENERATED by scripts/build-entity-index.ts. Do not edit by hand.
 * Re-run the script after adding a new LP, service, industry, platform,
 * case study, or diagram.
 */
import type { PanelType } from '@/components/copilot/panels/registry';

export interface EntityIndexEntry {
  panelType: PanelType;
  title: string;
}

export const ENTITY_INDEX: Readonly<Record<string, EntityIndexEntry>> = {
  "data-engineering-services": {
    "panelType": "resource",
    "title": "Transform Your Data Infrastructure"
  },
  "power-bi-consulting": {
    "panelType": "resource",
    "title": "Unlock the Power of Your Data with Power BI"
  },
  "cloud-migration-services": {
    "panelType": "resource",
    "title": "Migrate to Cloud with Confidence"
  },
  "dynamics-365-implementation": {
    "panelType": "resource",
    "title": "Accelerate Your Digital Transformation with Dynamics 365"
  },
  "generative-ai-consulting": {
    "panelType": "resource",
    "title": "Harness the Power of Generative AI"
  },
  "ai-ml-implementation": {
    "panelType": "resource",
    "title": "Turn Your Data Into Intelligent Decisions"
  },
  "agentic-ai-development": {
    "panelType": "resource",
    "title": "Build AI Agents That Work For You"
  },
  "data-integration-services": {
    "panelType": "resource",
    "title": "Connect Your Data, Unlock Its Value"
  },
  "data-observability-platform": {
    "panelType": "resource",
    "title": "Trust Your Data With Complete Visibility"
  },
  "erp-modernization-services": {
    "panelType": "resource",
    "title": "Modernize Your ERP Without Disrupting Operations"
  },
  "snowflake-consulting": {
    "panelType": "resource",
    "title": "Maximize Your Snowflake Investment"
  },
  "databricks-services": {
    "panelType": "resource",
    "title": "Build Your Data Lakehouse with Databricks"
  },
  "databricks-migration": {
    "panelType": "resource",
    "title": "Migrate to Databricks Lakehouse — Zero Downtime, Full Confidence"
  },
  "databricks-unity-catalog": {
    "panelType": "resource",
    "title": "Implement Unity Catalog Before the Deadline Hits"
  },
  "databricks-genai": {
    "panelType": "resource",
    "title": "Build Enterprise GenAI on Databricks — From POC to Production"
  },
  "databricks-cost-optimization": {
    "panelType": "resource",
    "title": "Cut Your Databricks Costs by 40-60% — Without Sacrificing Performance"
  },
  "databricks-mlops": {
    "panelType": "resource",
    "title": "Get ML Models from Notebook to Production on Databricks"
  },
  "data-pipeline-development": {
    "panelType": "resource",
    "title": "Build Data Pipelines That Never Fail"
  },
  "etl-services": {
    "panelType": "resource",
    "title": "ETL Services That Scale With Your Business"
  },
  "power-bi-dashboard-development": {
    "panelType": "resource",
    "title": "Custom Power BI Dashboards That Drive Decisions"
  },
  "power-bi-implementation": {
    "panelType": "resource",
    "title": "Enterprise Power BI Implementation Done Right"
  },
  "azure-migration-services": {
    "panelType": "resource",
    "title": "Migrate to Azure with Microsoft Experts"
  },
  "aws-migration-partner": {
    "panelType": "resource",
    "title": "Migrate to AWS with Certified Experts"
  },
  "cloud-cost-optimization": {
    "panelType": "resource",
    "title": "Cut Your Cloud Costs by 30-50%"
  },
  "dynamics-365-finance-implementation": {
    "panelType": "resource",
    "title": "Transform Financial Operations with D365 Finance"
  },
  "dynamics-365-sales-consulting": {
    "panelType": "resource",
    "title": "Accelerate Sales with Dynamics 365 Sales"
  },
  "enterprise-chatbot-development": {
    "panelType": "resource",
    "title": "Build AI Chatbots That Actually Work"
  },
  "ai-copilot-development": {
    "panelType": "resource",
    "title": "Build AI Copilots for Your Workflows"
  },
  "predictive-analytics-services": {
    "panelType": "resource",
    "title": "Predict the Future with Your Data"
  },
  "mlops-services": {
    "panelType": "resource",
    "title": "Get ML Models to Production and Keep Them There"
  },
  "mulesoft-consulting": {
    "panelType": "resource",
    "title": "Unlock Connectivity with MuleSoft"
  },
  "api-integration-services": {
    "panelType": "resource",
    "title": "Connect Your Systems with Modern APIs"
  },
  "sap-s4hana-migration": {
    "panelType": "resource",
    "title": "Migrate to SAP S/4HANA with Confidence"
  },
  "netsuite-implementation": {
    "panelType": "resource",
    "title": "Fast-Track Your NetSuite Implementation"
  },
  "ai-automation-services": {
    "panelType": "resource",
    "title": "Automate Complex Work with AI"
  },
  "intelligent-process-automation": {
    "panelType": "resource",
    "title": "Transform Processes with Intelligent Automation"
  },
  "data-quality-services": {
    "panelType": "resource",
    "title": "Trust Your Data with Enterprise Data Quality"
  },
  "data-governance-consulting": {
    "panelType": "resource",
    "title": "Build a Data Governance Program That Works"
  },
  "salesforce-implementation": {
    "panelType": "resource",
    "title": "Maximize Your Salesforce Investment"
  },
  "salesforce-integration": {
    "panelType": "resource",
    "title": "Connect Salesforce to Your Entire Business"
  },
  "salesforce-marketing-cloud": {
    "panelType": "resource",
    "title": "Personalized Marketing at Scale with Marketing Cloud"
  },
  "servicenow-implementation": {
    "panelType": "resource",
    "title": "Transform IT Service Management with ServiceNow"
  },
  "servicenow-itsm": {
    "panelType": "resource",
    "title": "Modern IT Service Management with ServiceNow ITSM"
  },
  "servicenow-hr-service-delivery": {
    "panelType": "resource",
    "title": "Transform Employee Experience with ServiceNow HRSD"
  },
  "braze-implementation": {
    "panelType": "resource",
    "title": "Engage Customers Everywhere with Braze"
  },
  "braze-customer-engagement": {
    "panelType": "resource",
    "title": "Build Customer Relationships That Last"
  },
  "utilities-data-modernization": {
    "panelType": "resource",
    "title": "Modernize Your Utility Data Infrastructure"
  },
  "data-engineering": {
    "panelType": "service",
    "title": "Data Engineering"
  },
  "modernizes-finance-reporting-with-sap-transformation": {
    "panelType": "case",
    "title": "40+ finance systems post-acquisitions needed consolidation into unified platform"
  },
  "convenience-retailer-realtime-data": {
    "panelType": "case",
    "title": "Payment systems across 600+ locations needed real-time data with zero downtime"
  },
  "hospitality-leader-unified-data": {
    "panelType": "case",
    "title": "Global operations with data scattered across regional silos"
  },
  "applied-ai-ml": {
    "panelType": "service",
    "title": "Applied AI ML"
  },
  "financial-forecasting": {
    "panelType": "case",
    "title": "Forecasting models took weeks to retrain and deploy, missing market changes"
  },
  "retail-personalization": {
    "panelType": "case",
    "title": "Generic marketing driving customers to competitors"
  },
  "document-processing": {
    "panelType": "case",
    "title": "Manual claims processing taking 72 hours average"
  },
  "cloud-modernization": {
    "panelType": "service",
    "title": "Cloud Modernization"
  },
  "insurance-cloud-migration": {
    "panelType": "case",
    "title": "Legacy data center costing $20M annually with aging hardware"
  },
  "retail-modernization": {
    "panelType": "case",
    "title": "Monolithic e-commerce platform unable to handle peak traffic"
  },
  "manufacturing-multicloud": {
    "panelType": "case",
    "title": "Locked into single cloud vendor with no disaster recovery"
  },
  "martech-cdp": {
    "panelType": "service",
    "title": "MarTech CDP"
  },
  "convenience-retailer-martech": {
    "panelType": "case",
    "title": "Needed a unified digital guest experience and loyalty platform across 600+ locations with real-time personalization at the point of sale."
  },
  "hospitality-loyalty": {
    "panelType": "case",
    "title": "Loyalty program data siloed from marketing systems"
  },
  "digital-transformation": {
    "panelType": "service",
    "title": "Digital Transformation"
  },
  "finance-automation": {
    "panelType": "case",
    "title": "Manual accounts payable processing taking 5 days average"
  },
  "hr-transformation": {
    "panelType": "case",
    "title": "HR requests lost in email, no visibility on status"
  },
  "customer-service": {
    "panelType": "case",
    "title": "Claims processing backlog growing, customer complaints rising"
  },
  "cyber-security": {
    "panelType": "service",
    "title": "Cyber Security"
  },
  "healthcare-compliance": {
    "panelType": "case",
    "title": "HIPAA compliance gaps identified in security audit"
  },
  "financial-devsecops": {
    "panelType": "case",
    "title": "Security slowing down release cycles, developers bypassing controls"
  },
  "retail-zerotrust": {
    "panelType": "case",
    "title": "Breach concerns with remote workforce and third-party access"
  },
  "app-development": {
    "panelType": "service",
    "title": "App Development"
  },
  "quality-engineering": {
    "panelType": "service",
    "title": "Quality Engineering"
  },
  "financial-services": {
    "panelType": "industry",
    "title": "Financial Services Technology Solutions"
  },
  "asset-management-proof": {
    "panelType": "case",
    "title": "40+ finance systems post-acquisitions needed consolidation with zero disruption to financial reporting"
  },
  "banking-proof": {
    "panelType": "case",
    "title": "Rising fraud losses, slow manual review process, high false positive rates"
  },
  "healthcare": {
    "panelType": "industry",
    "title": "Healthcare & Life Sciences Technology Solutions"
  },
  "healthcare-provider-proof": {
    "panelType": "case",
    "title": "Fragmented patient data across 12 hospitals preventing coordinated care"
  },
  "life-sciences-proof": {
    "panelType": "case",
    "title": "Siloed research data slowing drug discovery timelines"
  },
  "retail": {
    "panelType": "industry",
    "title": "Retail & Consumer Technology Solutions"
  },
  "convenience-retail-proof": {
    "panelType": "case",
    "title": "Fragmented customer data across 800+ locations preventing personalized engagement"
  },
  "department-store-proof": {
    "panelType": "case",
    "title": "Manual forecasting causing $50M+ in inventory inefficiencies annually"
  },
  "manufacturing": {
    "panelType": "industry",
    "title": "Manufacturing Technology Solutions"
  },
  "discrete-manufacturing-proof": {
    "panelType": "case",
    "title": "Unplanned equipment failures causing significant production losses and safety risks"
  },
  "heavy-manufacturing-proof": {
    "panelType": "case",
    "title": "Quality issues not detected until final inspection, causing rework and delays"
  },
  "hospitality": {
    "panelType": "industry",
    "title": "Hospitality & Food Services Technology Solutions"
  },
  "global-food-services-proof": {
    "panelType": "case",
    "title": "Unify data across 400,000+ employees in 53 countries to enable real-time workforce analytics and operational visibility"
  },
  "hospitality-proof": {
    "panelType": "case",
    "title": "Fragmented guest data across properties preventing personalized experiences and loyalty optimization"
  },
  "energy": {
    "panelType": "industry",
    "title": "Energy & Utilities Technology Solutions"
  },
  "electric-utility-proof": {
    "panelType": "case",
    "title": "NERC CIP compliance gaps putting critical infrastructure at risk"
  },
  "gas-electric-proof": {
    "panelType": "case",
    "title": "Aging infrastructure causing unplanned outages and safety risks"
  },
  "transportation": {
    "panelType": "industry",
    "title": "Transportation & Logistics Technology Solutions"
  },
  "freight-logistics-proof": {
    "panelType": "case",
    "title": "Rising fuel costs and inefficient routing costing millions annually, with limited visibility into fleet performance"
  },
  "transportation-proof": {
    "panelType": "case",
    "title": "High maintenance costs and unexpected breakdowns disrupting operations and customer commitments"
  },
  "databricks": {
    "panelType": "platform",
    "title": "Databricks Implementation Services"
  },
  "retail-proof": {
    "panelType": "case",
    "title": "Low email engagement and no mobile push strategy"
  },
  "healthcare-proof": {
    "panelType": "case",
    "title": "On-premise infrastructure limiting ability to scale telehealth services"
  },
  "snowflake": {
    "panelType": "platform",
    "title": "Snowflake Implementation Services"
  },
  "financial-services-proof": {
    "panelType": "case",
    "title": "Manual IT processes causing slow ticket resolution and poor employee satisfaction"
  },
  "aws": {
    "panelType": "platform",
    "title": "AWS Cloud Services"
  },
  "azure": {
    "panelType": "platform",
    "title": "Microsoft Azure Cloud Services"
  },
  "manufacturing-proof": {
    "panelType": "case",
    "title": "No visibility into IT assets and infrastructure dependencies"
  },
  "salesforce": {
    "panelType": "platform",
    "title": "Salesforce Implementation Services"
  },
  "sap": {
    "panelType": "platform",
    "title": "SAP Implementation Services"
  },
  "servicenow": {
    "panelType": "platform",
    "title": "ServiceNow Implementation Services"
  },
  "braze": {
    "panelType": "platform",
    "title": "Braze Implementation Services"
  },
  "microsoft-dynamics": {
    "panelType": "platform",
    "title": "Microsoft Dynamics"
  },
  "d365-manufacturing-ordertocash": {
    "panelType": "case",
    "title": "Disconnected systems causing delays in order-to-cash cycle"
  },
  "d365-services-project-ops": {
    "panelType": "case",
    "title": "Manual resource allocation and project tracking"
  },
  "lakehouse": {
    "panelType": "diagram",
    "title": "lakehouse"
  },
  "data-mesh": {
    "panelType": "diagram",
    "title": "data-mesh"
  },
  "unity-catalog": {
    "panelType": "diagram",
    "title": "unity-catalog"
  },
  "cdp-flow": {
    "panelType": "diagram",
    "title": "cdp-flow"
  },
  "mlops-lifecycle": {
    "panelType": "diagram",
    "title": "mlops-lifecycle"
  },
  "agentic-loop": {
    "panelType": "diagram",
    "title": "agentic-loop"
  },
  "zero-trust": {
    "panelType": "diagram",
    "title": "zero-trust"
  },
  "migration-waves": {
    "panelType": "diagram",
    "title": "migration-waves"
  },
  "api-topology": {
    "panelType": "diagram",
    "title": "api-topology"
  },
  "retail-realtime": {
    "panelType": "diagram",
    "title": "retail-realtime"
  },
  "healthcare-data": {
    "panelType": "diagram",
    "title": "healthcare-data"
  },
  "erp-consolidation": {
    "panelType": "diagram",
    "title": "erp-consolidation"
  },
  "predictive-ops": {
    "panelType": "diagram",
    "title": "predictive-ops"
  },
  "observability": {
    "panelType": "diagram",
    "title": "observability"
  },
  "engagement-model": {
    "panelType": "diagram",
    "title": "engagement-model"
  }
} as const;

export function resolveEntity(entityRef: string): EntityIndexEntry | undefined {
  return ENTITY_INDEX[entityRef];
}
